//===- MicrokernelOps.td - microkernel dialect ops ---------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef MICROKERNEL_OPS
#define MICROKERNEL_OPS

#include "MicrokernelDialect.td"

#endif