//===- OnednnGraphOps.td - OneDNN input dialect ops --------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef ONEDNNGRAPH_OPS
#define ONEDNNGRAPH_OPS

include "OnednnGraphDialect.td"

#endif // ONEDNNGRAPH_OPS