include_guard()

macro(gc_set_mlir_link_components VAR)
  if(GC_DYLINK)
    set(${VAR} MLIR)
  else()
    set(${VAR} ${ARGN})
  endif()
endmacro()

function(gc_add_mlir_library name)
  if(GC_DYLINK AND NOT SHARED IN_LIST ARGN)
    add_mlir_library(${name} DISABLE_INSTALL ${ARGN})
  else()
    add_mlir_library(${ARGV})
  endif()

  if(name MATCHES ".+Passes")
    set_property(GLOBAL APPEND PROPERTY GC_PASS_LIBS ${name})
  else()
    set_property(GLOBAL APPEND PROPERTY GC_MLIR_LIBS ${name})
  endif()

  if(GcInterface IN_LIST ARGN)
    if(SHARED IN_LIST ARGN)
      target_link_libraries(${name} PUBLIC GcInterface)
    else()
      target_link_libraries(obj.${name} PUBLIC GcInterface)
    endif()
  endif()
endfunction()

function(gc_add_mlir_dialect_library name)
  if(GC_DYLINK)
    add_mlir_dialect_library(${name} DISABLE_INSTALL ${ARGN})
  else()
    add_mlir_dialect_library(${ARGV})
  endif()
  target_link_libraries(obj.${name} PUBLIC GcInterface)
  set_property(GLOBAL APPEND PROPERTY GC_DIALECT_LIBS ${name})

  if(GcInterface IN_LIST ARGN)
    target_link_libraries(obj.${name} PUBLIC GcInterface)
  endif()
endfunction()

function(gc_add_mlir_conversion_library name)
  if(GC_DYLINK)
    add_mlir_conversion_library(${name} DISABLE_INSTALL ${ARGN})
  else()
    add_mlir_conversion_library(${ARGV})
  endif()
  target_link_libraries(obj.${name} PUBLIC GcInterface)
  set_property(GLOBAL APPEND PROPERTY GC_PASS_LIBS ${name})

  if(GcInterface IN_LIST ARGN)
    target_link_libraries(obj.${name} PUBLIC GcInterface)
  endif()
endfunction()

function(gc_add_mlir_translation_library name)
  if(GC_DYLINK)
    add_mlir_translation_library(${name} DISABLE_INSTALL ${ARGN})
  else()
    add_mlir_translation_library(${ARGV})
  endif()
  target_link_libraries(obj.${name} PUBLIC GcInterface)
  set_property(GLOBAL APPEND PROPERTY GC_MLIR_LIBS ${name})

  if(GcInterface IN_LIST ARGN)
    target_link_libraries(obj.${name} PUBLIC GcInterface)
  endif()
endfunction()

macro(gc_add_mlir_tool name)
  add_mlir_tool(${ARGV})
  # LLVM_LINK_COMPONENTS is processed by LLVM cmake in add_llvm_executable
  target_link_libraries(${name} PRIVATE GcInterface ${MLIR_LINK_COMPONENTS})
  llvm_update_compile_flags(${name})
  set_property(GLOBAL APPEND PROPERTY GC_TOOLS ${name})
  set_target_properties(${name} PROPERTIES EXCLUDE_FROM_ALL OFF)
  target_compile_options(${name} PRIVATE -ffunction-sections -fdata-sections)
  target_link_options(${name} PRIVATE -Wl,--gc-sections -Wl,--as-needed)
  mlir_check_all_link_libraries(${name})
endmacro()

macro(gc_link_mlir_tool name)
  if(GC_DYLINK)
    target_link_libraries(${name} PRIVATE ${PROJECT_NAME})
  else()
    target_link_libraries(${name} PRIVATE ${ARGN})
  endif()
endmacro()
