name: Python Format

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  python_format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout base version
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.base.sha }}
      
      - name: checkout head version
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: install darker
        run: "python3 -m pip install darker"
      
      - name: check python format
        run: "python3 -m darker --check --diff -r `git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}`...HEAD ."